spring: 
  datasource:
   driver-class-name: org.h2.Driver
   url: jdbc:h2:mem:testdb
   username: sa
   password:
   
gateway:
  ip: 192.168.0.1.03

token:
  expiration_time: 864000000
  secret: sdafknqewoifnqoinrio21j45oi14j5623ktnoqwerinfgorisngsadfknewlknfioqwenfoisndfmy_token_chaged#1