spring: 
  datasource:
   driver-class-name: org.h2.Driver
   url: jdbc:h2:mem:testdb
   username: '{cipher}cb76e21f29ddcb74bbf7c68596c8826f3f04d98f75921d56379bc1ac75e2a89f'
   password:

gateway:
  ip: 192.168.0.1.03

token:
  expiration_time: 864000000
  secret: sdafknqewoifnqoinrio21j45oi14j5623ktnoqwerinfgorisngsadfknewlknfioqwenfoisndfmy_token_chaged#1